import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TooltipModule } from "ngx-tooltip";
import { PopoverModule } from "ngx-popover";
import { Uploader }      from 'angular2-http-file-upload';
import { Daterangepicker } from 'ng2-daterangepicker';
import { Ng2DatetimePickerModule } from 'ng2-datetime-picker';
import { ChartModule } from 'angular2-chartjs';

import * as cmp from './';
import * as pip from './../@pipes';
import * as child from './../+dashboard/exports';

@NgModule({
    declarations: [
            // Components / Directives/ Pipes
            child.SaleReportComponent,
            child.BookKeppingReportComponent,
            child.PurchaseReportComponent,
            child.BanksDetailsComponent,
            child.BanksListComponent,
            child.BranchesDetailsComponent,
            child.BranchesListComponent,
            child.ContactsReportComponent,
            child.ProductsReportComponent,
            child.WalletReportComponent,
            child.ResultsReportComponent,
            child.ReportsListComponent,
            child.TaxesDetailsComponent,
            child.TaxesListComponent,
            child.TypesDetailsComponent,
            child.TypesListComponent,
            child.ProductsDetailsComponent,
            child.ProductsListComponent,
            child.TrashDetailsComponent,
            child.TrashListComponent,
            child.HistoryListComponent,
            child.TimerListComponent,
            child.TimerDetailsComponent,
            child.PurchasesDetailsComponent,
            child.PurchasesListComponent,
            child.PurchasesShowsComponent,
            child.SalesDetailsComponent,
            child.SalesListComponent,
            child.SalesShowsComponent,
            child.RegistersDetailsComponent,
            child.RegistersListComponent,
            child.RegistersHistoryDetailsComponent,
            child.RegistersHistoryListComponent,
            child.SuppliersDetailsComponent,
            child.SuppliersListComponent,
            child.EmployeesDetailsComponent,
            child.EmployeesListComponent,
            child.ExpensesDetailsComponent,
            child.ExpensesListComponent,
            child.PaidsDetailsComponent,
            child.PaidsListComponent,
            child.CustomersDetailsComponent,
            child.CustomersListComponent,
            child.CollectionsDetailsComponent,
            child.CollectionsListComponent,
            child.BrandsDetailsComponent,
            child.BrandsListComponent,
            child.OptionsDetailsComponent,
            child.OptionsListComponent,
            child.UsersListComponent,
            child.UsersDetailsComponent,
            child.UsersPremessionsComponent,
            child.BookKeppingListComponent,
            child.BookKeppingDetailsComponent,
            child.BooksTreeListComponent,
            child.BooksTreeDetailsComponent,
            child.SettingsDetailsComponent,
            child.StoragesListComponent,
            child.StoragesDetailsComponent,
            child.AccountsDetailsComponent,
            child.AccountsListComponent,
            child.GiftsDetailsComponent,
            child.GiftsListComponent,
            child.JournalsDetailsComponent,
            child.JournalsListComponent,
            //----------------------------------------
            cmp.AutocompleteComponent,
            cmp.ProDetailsComponent,
            cmp.ReportFilterComponent,
            cmp.DashboardActionsComponent,
            cmp.AddNewComponent,
            cmp.ShowItemComponent,
            cmp.SelectComponent,
            cmp.KeysComponent,
            cmp.OrdersAutocompleteComponent,
            cmp.DashboardFooterComponent,
            cmp.ReportFilterComponent,
            cmp.RainbowColorsComponent,
            cmp.ChartsComponent,
            cmp.BookTreeComponent,
            //----------------------------------------
            pip.CapitalizePipe ,
            pip.MyCurrencyPipe,
            pip.ReportSrc,
            pip.MyTimerPipe,
            pip.MyPaymentTypesPipe
        ],
    providers : [ Uploader] ,
    imports: [
        CommonModule, ReactiveFormsModule, FormsModule, TooltipModule ,
        PopoverModule , Daterangepicker , Ng2DatetimePickerModule //,ChartsModule
        , ChartModule
        //, MyDatePickerModule
    ],
    exports : [

        child.SaleReportComponent,
        child.BookKeppingReportComponent,
        child.PurchaseReportComponent,
        child.BanksDetailsComponent,
        child.BanksListComponent,
        child.BranchesDetailsComponent,
        child.BranchesListComponent,
        child.ContactsReportComponent,
        child.ProductsReportComponent,
        child.WalletReportComponent,
        child.ResultsReportComponent,
        child.ReportsListComponent,
        child.TaxesDetailsComponent,
        child.TaxesListComponent,
        child.TypesDetailsComponent,
        child.TypesListComponent,
        child.ProductsDetailsComponent,
        child.ProductsListComponent,
        child.TrashDetailsComponent,
        child.TrashListComponent,
        child.HistoryListComponent,
        child.TimerListComponent,
        child.TimerDetailsComponent,
        child.PurchasesDetailsComponent,
        child.PurchasesListComponent,
        child.PurchasesShowsComponent,
        child.SalesDetailsComponent,
        child.SalesListComponent,
        child.SalesShowsComponent,
        child.RegistersDetailsComponent,
        child.RegistersListComponent,
        child.RegistersHistoryDetailsComponent,
        child.RegistersHistoryListComponent,
        child.SuppliersDetailsComponent,
        child.SuppliersListComponent,
        child.EmployeesDetailsComponent,
        child.EmployeesListComponent,
        child.ExpensesDetailsComponent,
        child.ExpensesListComponent,
        child.PaidsDetailsComponent,
        child.PaidsListComponent,
        child.CustomersDetailsComponent,
        child.CustomersListComponent,
        child.CollectionsDetailsComponent,
        child.CollectionsListComponent,
        child.BrandsDetailsComponent,
        child.BrandsListComponent,
        child.OptionsDetailsComponent,
        child.OptionsListComponent,
        child.UsersListComponent,
        child.UsersDetailsComponent,
        child.UsersPremessionsComponent,
        child.BookKeppingListComponent,
        child.BookKeppingDetailsComponent,
        child.BooksTreeListComponent,
        child.BooksTreeDetailsComponent,
        child.SettingsDetailsComponent,
        child.StoragesListComponent,
        child.StoragesDetailsComponent,
        child.AccountsDetailsComponent,
        child.AccountsListComponent,
        child.GiftsDetailsComponent,
        child.GiftsListComponent,
        child.JournalsDetailsComponent,
        child.JournalsListComponent,
        // ----------------------------------------
        cmp.AutocompleteComponent,
        cmp.ProDetailsComponent,
        cmp.DashboardActionsComponent,
        cmp.AddNewComponent,
        cmp.ShowItemComponent,
        cmp.SelectComponent,
        cmp.KeysComponent,
        cmp.OrdersAutocompleteComponent,
        cmp.DashboardFooterComponent,
        cmp.ReportFilterComponent,
        cmp.RainbowColorsComponent,
        cmp.ChartsComponent,
        cmp.BookTreeComponent,
        //----------------------------------------
        pip.CapitalizePipe ,
        pip.MyCurrencyPipe,
        pip.ReportSrc,
        pip.MyTimerPipe,
        pip.MyPaymentTypesPipe


    ]
})
export class DashboardComponentsModule{ }
